1. Le nom des villes (du Nord) par ordre alphabétique
2. Le code et le nom des villes dont le nom contient la lettre 'z' (éventuellement majuscule) ou commence par un 'T'
3. Les différents intitulés (sans répétitions) des catégories socio-professionnelles par ordre alphabétique
4. Le code INSEE de la ville de 'Caullery' ?
5. La(es) ville(s) dont le nom compte(nt) 5 lettres exactement
6. Toutes les informations (de la table évolution) pour la ville dont le code INSEE est 59140, triées par effectifs croissants.
7. Ajouter l’enregistrement suivant à la table ville : (35000, 'Rennes', 50.291048, 2.7772211)
8. Modifier le nom de cette nouvelle ville en la nommant 'New-York'.
9. Dans la table ville, renommer la colonne nom en nomVille
10. Supprimer les enregistrements pour les villes de 'New-York' et 'Lille'.